### ISSUE TITLE
Send multiple pixels per event & explore move to Javascript Implementation

### ISSUE THREAD

**Issue by sperand-io** [segment-integrations/analytics.js-integration-twitter-ads#2]
Appears that we're only hitting one of two pixel endpoints that their `<noscript>` falls back to:

![](https://cloudup.com/cZ3uZjILOGk+)

Specifically, we're **not** loading the second img w src `//t.co/i/adsct?etc`

---

Further, not sure whether it's deliberate that we're even using the  `<noscript>`'s `<img />` fallbacks in lieu of the js library, and if so why we did so in this particular case and not in others (ie. fb). Seems at least worth clarifying somewhere.

It does lighten page load, but I have to assume that the js "pixel" implementation exists and falls back to the img approach for a reason.

**Comment by hankim813** [comment]
done :)
