### ISSUE TITLE
New Twitter Universal tag

### ISSUE THREAD

**Issue by samuellavoie** [segment-integrations/analytics.js-integration-twitter-ads#4]
Twitter updated their advertising pixel to an universal tag (finally!)

https://blog.twitter.com/2016/website-conversion-tracking-and-remarketing-made-easier-and-more-flexible

**Comment by hankim813** [comment]
@samuellavoie sweet I just added this to our Integrations team's list of updates! Just want to let you know :)

**Comment by hankim813** [comment]
shipped in #8
